# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_auth',
            name='protem_token',
            field=models.CharField(max_length=50),
        ),
    ]
