# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brith_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
