# Generated by Django 2.1.3 on 2019-01-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='email_auth',
            table=None,
        ),
    ]
