# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20180616_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_auth',
            name='email',
        ),
        migrations.RemoveField(
            model_name='email_auth',
            name='password',
        ),
        migrations.RemoveField(
            model_name='email_auth',
            name='protem_token',
        ),
        migrations.RemoveField(
            model_name='email_auth',
            name='username',
        ),
        migrations.AddField(
            model_name='email_auth',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
