# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181114_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('F', 'favorite'), ('U', 'up vote'), ('D', 'down vote')], max_length=1),
        ),
    ]
