# Generated by Django 2.1.3 on 2019-01-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_email_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_auth',
            name='user',
        ),
        migrations.DeleteModel(
            name='Email_auth',
        ),
    ]
