# Generated by Django 2.1.3 on 2019-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190213_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='treecontent',
            name='quote',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
