# Generated by Django 2.1.1 on 2019-06-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_location'),
        ('core', '0006_treecontent_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_city',
            name='county',
        ),
        migrations.RemoveField(
            model_name='country_county',
            name='province',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.DeleteModel(
            name='Country_city',
        ),
        migrations.DeleteModel(
            name='Country_county',
        ),
        migrations.DeleteModel(
            name='Country_province',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
