# Generated by Django 2.1.3 on 2019-02-01 07:07

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymedia',
            name='post',
        ),
        migrations.RemoveField(
            model_name='studypostbase',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='studypost',
            name='post',
        ),
        migrations.AddField(
            model_name='studypost',
            name='content',
            field=markdownx.models.MarkdownxField(default='test'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudyMedia',
        ),
        migrations.DeleteModel(
            name='StudyPostBase',
        ),
    ]
