# Generated by Django 2.1.3 on 2018-12-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('course', '0002_auto_20181116_0907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyImage',
            new_name='StudyMedia',
        ),
        migrations.RemoveField(
            model_name='studyvideo',
            name='post',
        ),
        migrations.AlterModelOptions(
            name='studymedia',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Mediums'},
        ),
        migrations.AddField(
            model_name='studypost',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.LessonTree'),
        ),
        migrations.DeleteModel(
            name='StudyVideo',
        ),
    ]
