# Generated by Django 2.1.1 on 2019-06-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='add_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='add_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='slug',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='title',
            field=models.CharField(default=23123, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
