# Generated by Django 2.1.3 on 2019-07-19 07:17

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('studypost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='no_image', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(default='no_image', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesubpost',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_posts', to='studypost.Course'),
        ),
        migrations.AddField(
            model_name='coursesubpost',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.LessonTree'),
        ),
    ]
