# Generated by Django 2.1.3 on 2019-02-09 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_treecontent_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studypost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='magazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('add_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.LessonTree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='StudyPost',
            new_name='course',
        ),
    ]
