# Generated by Django 2.1.3 on 2019-01-27 19:25

from django.db import migrations
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=markdownx.models.MarkdownxField(default='sdfersddfg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=markdownx.models.MarkdownxField(default='sdfer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
