# Generated by Django 2.1.3 on 2019-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treecontent',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
