# Generated by Django 2.1.3 on 2019-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_treecontent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_city',
            name='slug',
            field=models.CharField(default='test', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country_county',
            name='slug',
            field=models.CharField(default='test', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country_province',
            name='slug',
            field=models.CharField(default='wdcer', max_length=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country_city',
            name='name',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='country_county',
            name='name',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='country_province',
            name='name',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='location',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
