# Generated by Django 2.1.3 on 2019-02-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190210_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='path_slug',
            field=models.CharField(default='resrt', max_length=255),
            preserve_default=False,
        ),
    ]
