# Generated by Django 2.1.3 on 2019-02-13 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_location_path_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('F', 'favorite'), ('U', 'up vote'), ('D', 'down vote')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='treecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='country_city',
            name='slug',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='country_county',
            name='slug',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='country_province',
            name='slug',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='location',
            name='path_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
