# Generated by Django 2.1.1 on 2019-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20190205_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='key',
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
