# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-04 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct_answer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Exponential_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exponential_answers/images')),
                ('video', models.FileField(blank=True, null=True, upload_to='exponential_answers/videos')),
                ('extra', models.FileField(blank=True, null=True, upload_to='exponential_answers/extras')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('total_votes', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quizzes/images')),
                ('level', models.CharField(choices=[('VH', 'very hard'), ('H', 'hard'), ('M', 'medium'), ('E', 'easy'), ('VE', 'very easy')], max_length=2)),
                ('time_for_out', models.TimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exponential_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Exponential_answer')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LessonTree')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Quiz_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz')),
                ('user_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Answer')),
            ],
            options={
                'verbose_name_plural': 'Quizzes statuses',
            },
        ),
        migrations.CreateModel(
            name='QuizzesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('close_date', models.DateTimeField()),
                ('key', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField()),
                ('quizzes_status', models.ManyToManyField(blank=True, to='quizzes.Quiz_status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TreeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('G', 'grade'), ('L', 'lesson'), ('C', 'chapter'), ('T', 'topic')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Source'),
        ),
        migrations.AddField(
            model_name='lessontree',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.TreeContent'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz'),
        ),
    ]
