# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Exponential_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exponential_answers/images')),
                ('video', models.FileField(blank=True, null=True, upload_to='exponential_answers/videos')),
                ('extra', models.FileField(blank=True, null=True, upload_to='exponential_answers/extras')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Grade')),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Quizze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('correct_answer', models.IntegerField()),
                ('exponential_answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Exponential_answer')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Level')),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Chapter')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Grade')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Lesson')),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.AddField(
            model_name='quizze',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Source'),
        ),
        migrations.AddField(
            model_name='quizze',
            name='topic',
            field=models.ManyToManyField(to='quizzes.Topic'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Grade'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Lesson'),
        ),
    ]
