# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-10 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Exponential_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exponential_answers/images')),
                ('video', models.FileField(blank=True, null=True, upload_to='exponential_answers/videos')),
                ('extra', models.FileField(blank=True, null=True, upload_to='exponential_answers/extras')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('grade', models.ManyToManyField(to='quizzes.Grade')),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='quizzes/images')),
                ('level', models.CharField(choices=[('VH', 'very hard'), ('H', 'hard'), ('M', 'medium'), ('E', 'easy'), ('VE', 'very easy')], max_length=5)),
                ('timeOut', models.DateTimeField(blank=True, null=True)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='quizzes.Answers')),
                ('exponential_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Exponential_answer')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Grade')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Lesson')),
                ('quiz_answers', models.ManyToManyField(to='quizzes.Answers')),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='Quizzes_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quizzes')),
                ('user_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Answers')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Chapter')),
                ('grade', models.ManyToManyField(to='quizzes.Grade')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Lesson')),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.AddField(
            model_name='quizzes',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Source'),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='topics',
            field=models.ManyToManyField(blank=True, to='quizzes.Topic'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='grade',
            field=models.ManyToManyField(to='quizzes.Grade'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Lesson'),
        ),
    ]
