# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='grade',
            new_name='grades',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='grade',
            new_name='grades',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='grade',
            new_name='grades',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
