# Generated by Django 2.1.3 on 2019-02-01 07:07

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='text',
        ),
        migrations.AddField(
            model_name='answer',
            name='content',
            field=markdownx.models.MarkdownxField(default='t'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='content',
            field=markdownx.models.MarkdownxField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='exponential_answer',
            field=markdownx.models.MarkdownxField(default='t'),
            preserve_default=False,
        ),
    ]
