# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test_quiz',
            new_name='quizzes',
        ),
    ]
