# Generated by Django 2.1.3 on 2019-02-05 14:42

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='exponential_answer',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
