# Generated by Django 2.1.3 on 2019-01-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_score', models.PositiveIntegerField()),
                ('positive_score', models.PositiveIntegerField()),
                ('total_score', models.IntegerField()),
                ('advise', models.IntegerField()),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Exam')),
            ],
        ),
    ]
