# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-14 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20181113_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_for_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
