# Generated by Django 2.1.3 on 2019-01-12 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_examstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
