# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20180605_0648'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grades',
            table='grade',
        ),
        migrations.AlterModelTable(
            name='lessons',
            table='lesson',
        ),
        migrations.AlterModelTable(
            name='levels',
            table='level',
        ),
        migrations.AlterModelTable(
            name='quizzes',
            table='quizze',
        ),
        migrations.AlterModelTable(
            name='sources',
            table='source',
        ),
    ]
