# Generated by Django 2.1.3 on 2019-01-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_exam_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examstatistic',
            name='advise',
        ),
        migrations.AddField(
            model_name='quizstatus',
            name='did_user_answer',
            field=models.BooleanField(default=False),
        ),
    ]
