# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20181114_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='exponential_answer',
        ),
        migrations.DeleteModel(
            name='Exponential_answer',
        ),
    ]
