# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20181116_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz')),
            ],
            options={
                'verbose_name_plural': 'Quizzes Statuses',
            },
        ),
        migrations.RemoveField(
            model_name='quiz_status',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz_status',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='quizzesinfo',
            name='quizzes_status',
        ),
        migrations.DeleteModel(
            name='Quiz_status',
        ),
        migrations.AddField(
            model_name='quizstatus',
            name='quizzes_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizzesInfo'),
        ),
        migrations.AddField(
            model_name='quizstatus',
            name='user_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Answer'),
        ),
    ]
