# Generated by Django 2.1.3 on 2018-11-25 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0006_auto_20181117_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizzesInfo',
            new_name='Exam',
        ),
        migrations.AlterModelOptions(
            name='quizstatus',
            options={'verbose_name_plural': 'Quizzes_Statuses'},
        ),
        migrations.RenameField(
            model_name='quizstatus',
            old_name='quizzes_info',
            new_name='exam',
        ),
    ]
